version: '3.9'

services:
  bayut-client:
    container_name: bayut-client
    build: 
      context: .
    env_file:
      - .env.local
    networks:
      - bayut
    
    nginx:
      container_name: bayut-nginx
      image: nginx:1.19.6-alpine
      ports:
        - 80:80
      volumes:
        - ./bayut.conf:/etc/nginx/conf.d/bayut.conf
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        
      networks:
        - bayut
      depends_on:
        - bayut-client
networks:
  bayut:
    external: true