version: '3.9'

services:
  bayut-client:
    container_name: bayut-client
    build: 
      context: .
    env_file:
      - .env.local
    networks:
      - bayut
    ports:
      - 80:3000
networks:
  bayut:
    external: true