version: '3.9'

services:
  bayut-client:
    container_name: bayut-client
    build: 
      context: .
    env_file:
      - .env.local
   
    networks:
      - bayut
networks:
  bayut:
    external: true